base/urls.py
from django.urls import path
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.home, name='home'),
    path('create-room/', views.create_room, name='create-room'),
    path('room/<int:pk>/', views.roompage, name='room-page'),
    path('update-room/<int:pk>', views.update_room, name='update-room'),
    path('login-page/', views.login_page, name='login-page'),
    path('logout-page/', views.logout_page, name='logout-page'),
    path('signup-page/', views.signup_page, name='signup-page'),
    path('profile-page/<int:pk>', views.profile_page, name='profile-page'),
    path('edit-user/<int:pk>', views.edit_user, name='edit-user'),
    path('delete-message/<int:pk>', views.delete_message, name='delete-message'),
    path('delete-room/<int:pk>', views.delete_room, name='delete-room'),
    path('topic-page/', views.topic_page, name='topic-page'),
]

studybud/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser



class User_detail(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatar", default="avatar.svg", blank=True, null=True)
    bio = models.CharField(max_length=1000, blank=True, null=True)
    
    def __str__(self):
        return str(self.user)

class Topic(models.Model):
    name = models.CharField(max_length=1000)
    def __str__(self):
        return str(self.name)

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)


    def __str__(self):
        return str(self.name)


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
   

    def __str__(self):
        return str(self.body[0:50])

base/forms.py
from django import forms
from .models import *
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

base/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Q
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as dj_login
from django.contrib.auth import logout as dj_logout
from time import sleep
from django.contrib.auth.models import User



# Create your views here.



# @login_required(login_url="login")
def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            dj_login(request, user)
            return redirect("home")
        else:
            messages.error(request, 'No! Account Founded')
    context = {

    }
    return render(request, "login.html", context)



# @login_required(login_url="login")
def signup_page(request):

    sign_up = True
    if request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
        f_name = request.POST.get('f_name')
        l_name = request.POST.get('l_name')
        
        try: 
            match_email = User.objects.get(email=email)
        except:
            match_email = None
        
        try: 
            match_username = User.objects.get(username=username)
        except:
            match_username = None


        if password!=password2:
            messages.error(request, 'Password Not Matching')
        
        if match_email != None:
            messages.error(request, 'Please Use a Different Email')

        if match_username != None:
            # sleep(1)
            messages.error(request, 'Please Use a Different Username')
            return redirect("signup-page")


        user = User.objects.create_user(username.lower(), email, password)
        user.first_name = f_name
        user.last_name = l_name
        user.save()
        user_details = User_detail.objects.create(user=user)
        user_details.save()

        user = authenticate(username=username, password=password)
        if user is not None:
            dj_login(request, user)

        

    # f = UserCreationForm()
    # if request.method == "POST":
    #     f = UserCreationForm(request.POST)
    #     if f.is_valid():
    #         f.save()
    #         # login(request, user)
    #         return redirect('home')
    #     else:
    #         messages.error(request, 'Try a Different Username')

    context = {
    "sign_up": sign_up,
    # "forms":f,
    }


        # user = authenticate(username=username, password=password)
    
    return render(request, "login.html", context)


# @login_required(login_url="login")
def logout_page(request):
    dj_logout(request)
    context = {

    }
    return redirect('login-page')


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) 
    ).order_by('created').reverse()
    topics = Topic.objects.all()[0:5]
    room_count = Room.objects.all().count()
    activity_logs = Message.objects.all().order_by('created').reverse()[:10]
    context = {
        "rooms":rooms,
        "topics":topics,
        "room_count":room_count,
        "activity_logs":activity_logs,
    }

    return render(request, 'home.html', context)


@login_required(login_url="login-page")
def create_room(request):
    if request.method == "POST":
        topic_name = request.POST.get('topic_name')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        Room.objects.create(
        host = request.user,
        name = request.POST.get('room_name'),
        topic =topic,
        )
        return redirect("home")
    topics = Topic.objects.all()
    context = {
        "topics":topics
    }
    return render(request, "create-room.html", context)


# @login_required(login_url="login-page")
def roompage(request,pk):
    room = Room.objects.get(id=pk)
    messages = room.message_set.all()
    participants = room.participants.all()
    if request.method == "POST":
        message = Message.objects.create(
            user = request.user,
            room = room,
            body = request.POST.get('message')
        )
        room.participants.add(request.user)

        return redirect("room-page", pk=room.id)
    context = {
        "room":room,
        "messages":messages,
        "participants":participants,
    }

    return render(request, "room.html", context)



# @login_required(login_url="login-page")
def update_room(request,pk):
    room = Room.objects.get(id=pk)
    topics = Topic.objects.all()
    context = {
        "room":room,
        "topics":topics
    }
    if request.method == "POST":
        name = request.POST.get('room_name')
        topic_name = request.POST.get('topic_name')
        room.topic, created = Topic.objects.get_or_create(name=topic_name)  
        room.name = name
        room.save()
        return redirect("room-page", pk=room.id)


    return render(request, "create-room.html", context)




def profile_page(request,pk):
    profile = User.objects.get(id=pk)
    activity_logs = Message.objects.all().order_by('created').reverse()
    topics = Topic.objects.all()[0:5]
    room_count = Room.objects.all().count()
    rooms = profile.room_set.all()
    context = {
        "topics":topics,
        "room_count":room_count,
        "profile":profile,
        "activity_logs":activity_logs,
        "rooms":rooms
    }
    return render(request, "profile.html", context)

def edit_user(request, pk):
    editing_user = User.objects.get(id=pk)
    editing_user_details = User_detail.objects.get(user=editing_user)
    if (request.user) != editing_user:
        return redirect("home")
    else:
        if request.method == "POST":
            try:
                editing_user_details.avatar = request.FILES["avatar"]
            except:
                pass
            editing_user_details.bio = request.POST.get("user_bio")
            editing_user.username = request.POST.get("username")
            editing_user.email = request.POST.get("email")

            editing_user.save()
            editing_user_details.save()

            return redirect(request.META.get('HTTP_REFERER'))


# name = request.POST.get('room_name')
#         topic_name = request.POST.get('topic_name')
#         room.topic, created = Topic.objects.get_or_create(name=topic_name)  
#         room.name = name
#         room.save()
    context = {
        "editing_user":editing_user
    }

    return render(request, "edit-user.html", context)

def delete_message(request, pk):
    del_message = Message.objects.get(id=pk)
    if request.user != del_message.user:
        return redirect("home")
    if request.method == "POST":
        del_message.delete()
        return redirect("home")
    context = {
        "obj":del_message
    }
    return render(request, "delete.html", context)

def delete_room(request, pk):
    del_room = Room.objects.get(id=pk)
    if request.user != del_room.host:
        return redirect("home")
    if request.method == "POST":
        del_room.delete()
        return redirect("home")
    context = {
        "obj":del_room
    }
    return render(request, "delete.html", context)

def topic_page(request):
    
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) 
    ).order_by('created').reverse()

    topics = Topic.objects.all()
    room_count = Room.objects.all().count()
    context = {
        "topics":topics,
        "room_count":room_count,

        }
    return render(request, "topics.html", context)

templates/activity_component.html
 <!-- Activities Start -->
 
 
 <div class="activities">
   <div class="activities__header">
     <h2>Recent Activities</h2>
     
     {% for activity in activity_logs %}
   <div class="activities__box">
     <div class="activities__boxHeader roomListRoom__header">
       <a href="{% url 'profile-page' activity.user.id %}" class="roomListRoom__author">
         <div class="avatar avatar--small">
           <img src="{{ activity.user.user_detail_set.all.first.avatar.url }}" />
         </div>
         <p>
           @{{activity.user}}
           <span>{{activity.created | timesince}}</span>
         </p>
       </a>
       <div class="roomListRoom__actions">
         {% if request.user == activity.user %}      
         <a href="{% url 'delete-message' activity.id %}">
           <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
        {% endif %}
       </div>
     </div>
     <div class="activities__boxContent">
       <p>replied to post <a href="{% url 'room-page' activity.room.id %}">{{activity.room}}</a></p>
       <div class="activities__boxRoomContent">
         {{activity.body|slice:"0:50"}}
       </div>
     </div>


 </div>
 <!-- Activities End -->
 {% endfor %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <title>StudyBuddy - Find study partners around the world!</title>
</head>

<body>
  <header class="header header--loggedIn">
    <div class="container">
      <a href="/" class="header__logo">
        <img src="{% static 'assets/logo.svg' %} " />
        <h1>StudyBuddy</h1>
      </a>
      <form class="header__search" method="GET" action="">
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
            </path>
          </svg>
          <input name="q" placeholder="Search for rooms..." />
        </label>
      </form>
      <nav class="header__menu">

        {% if user.is_authenticated %}

        <div>


          <div class="header__user">
            <a href="{% url 'profile-page' request.user.id %}">
              <div class="avatar avatar--medium active">
                
                <img src="{{ request.user.user_detail_set.all.first.avatar.url }}" alt="">

              </div>

              <p>{{request.user.username}} <span>@{{request.user.username}}</span></p>
            </a>
            <button class="dropdown-button">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>chevron-down</title>
                <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
              </svg>
            </button>
          </div>

          <div class="dropdown-menu">
            <a href="{% url 'edit-user' request.user.id %}" class="dropdown-link"><svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                width="32" height="32" viewBox="0 0 32 32">
                <title>tools</title>
                <path
                  d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z">
                </path>
              </svg>
              Settings</a>
            <a href="{% url 'logout-page' %} " class="dropdown-link"><svg version="1.1"
                xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path
                  d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z">
                </path>
                <path
                  d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z">
                </path>
              </svg>
              Logout</a>
          </div>
        </div>



        {% else %}

        <!-- Not Logged In -->
        <a href="{% url 'login-page' %} ">
          <img src="{{ '/media/avatar.svg' }} " />
          <p>Login</p>
        </a>

        <!-- Logged In -->



        {% endif %}

      </nav>
    </div>
  </header>
  {% block body %}

  {% endblock body %}
  <script src="{% static 'js/script.js' %} "></script>
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
    

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="index.html">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="post">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}" ?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
    {% endblock body %}

templates/edit-user.html
{% extends 'base.html' %}
{% block body %}
  

    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="profile.html">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="{% url 'edit-user' editing_user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form__group">
                            <label for="avatar">Avatar</label>
                            <input id="avatar" name="avatar" type="file" />
                        </div>

              <div class="form__group">
                <label for="username">Username</label>
                <input id="username" value="{{editing_user.username}}" name="username" type="text" placeholder="E.g. John doe" />
              </div>

              <div class="form__group">
                <label for="email">Email</label>
                <input id="email" name="email" value="{{editing_user.email}}" type="text" placeholder="E.g. john@email.com" />
              </div>

                        <div class="form__group">
                            <label for="user_bio">Bio</label>
                            <textarea name="user_bio" id="user_bio" placeholder="Write about yourself...">{{editing_user.user_detail_set.all.first.bio}}</textarea>
                        </div>
                        <div class="form__action">
                            <a class="btn btn--dark" href="index.html">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>

{% endblock body %}

templates/home.html
{% extends 'base.html' %}
{% block body %}
  

    <main class="layout layout--3">
      <div class="container">

        {% include 'topic_component.html' %}

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{rooms.count}} Room Found</p>
            </div>
            <a class="btn btn--main" href="{% url 'create-room' %} ">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>




          {% for room in rooms %}
            
        
          <div class="roomListRoom">
            <div class="roomListRoom__header">
              <a href="{% url 'profile-page' room.host.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{ room.host.user_detail_set.all.first.avatar.url }}" />
                </div>
                <span>@{{room.host.username}}</span>
              </a>
              <div class="roomListRoom__actions">
                <span>{{room.created | timesince}}</span>
              </div>
            </div>
            <div class="roomListRoom__content">
              <a href="{% url 'room-page' room.id %} ">{{room.name}}</a>

            </div>
            <div class="roomListRoom__meta">
              <a href="{% url 'room-page' room.id %}" class="roomListRoom__joined">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>user-group</title>
                  <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                  ></path>
                  <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                  ></path>
                  <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                  ></path>
                  <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                  ></path>
                </svg>
                {{room.participants.count}} People Joined
              </a>
              <p class="roomListRoom__topic">{{room.topic}}</p>
            </div>
          </div>

          {% endfor %}



          
        </div>
        <!-- Room List End -->

       {% include 'activity_component.html' %}




      </div>
    </main>

    {% endblock body %}

templates/profile.html
{% extends 'base.html' %}
{% block body %}
  

  <main class="profile-page layout layout--3">
    <div class="container">
 {% include 'topic_component.html' %}


      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{profile.user_detail_set.all.first.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{profile.username}}</h3>
            <p>@{{profile.username}}</p>
            {% if request.user == profile %}
            <a href="{% url 'edit-user' profile.id %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{profile.username}}</a>
            </h2>
          </div>
        </div>


        {% for room in rooms %}
          
       
        <div class="roomListRoom">
          <div class="roomListRoom__header">
            <a href="{% url 'profile-page' profile.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small active">
                <img src="{{room.host.user_detail_set.all.first.avatar.url}}" />
              </div>
              <span>@{{room.host.username}}</span>
            </a>
            <div class="roomListRoom__actions">
              <span>{{room.created | timesince}}</span>

            </div>
          </div>
          <div class="roomListRoom__content">
            <a href="{% url 'room-page' room.id %}">{{room.name}}</a>
          </div>
          <div class="roomListRoom__meta">
            <a class="roomListRoom__joined">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                  d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                  d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                  d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                  d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
              </svg>
              {{room.participants.count}} People Joined
            </a>
            <p class="roomListRoom__topic">{{room.topic}}</p>
          </div>
        </div>




        {% endfor %}


      </div>
      <!-- Room List End -->
{% include 'activity_component.html' %}

    </div>
  </main>
  {% endblock body %}